// Service provider data from the provided list
export interface ServiceProvider {
  id: number
  name: string
  category: string
  phone: string
  email: string
  rating: number
  reviews: number
  description: string
  availability: string
  verified: boolean
}

export const serviceProviders: ServiceProvider[] = [
  // Groceries
  {
    id: 1,
    name: "FreshMart Groceries",
    category: "Groceries",
    phone: "+91-9876543210",
    email: "freshmart@store.com",
    rating: 4.6,
    reviews: 89,
    description: "Fresh groceries and daily essentials with home delivery",
    availability: "Daily 7AM-10PM",
    verified: true,
  },
  {
    id: 2,
    name: "GreenLeaf Organics",
    category: "Groceries",
    phone: "+91-9823456781",
    email: "contact@greenleaf.com",
    rating: 4.8,
    reviews: 156,
    description: "Organic fruits, vegetables and health foods",
    availability: "Daily 8AM-9PM",
    verified: true,
  },
  {
    id: 3,
    name: "DailyNeeds Superstore",
    category: "Groceries",
    phone: "+91-9845671234",
    email: "support@dailyneeds.com",
    rating: 4.5,
    reviews: 203,
    description: "One-stop shop for all household needs",
    availability: "Daily 6AM-11PM",
    verified: true,
  },
  {
    id: 4,
    name: "City Market",
    category: "Groceries",
    phone: "+91-9812345678",
    email: "citymarket@gmail.com",
    rating: 4.3,
    reviews: 127,
    description: "Local market with fresh produce and groceries",
    availability: "Daily 7AM-9PM",
    verified: false,
  },
  {
    id: 5,
    name: "Food Basket",
    category: "Groceries",
    phone: "+91-9876512345",
    email: "orders@foodbasket.com",
    rating: 4.7,
    reviews: 94,
    description: "Premium groceries with quick delivery service",
    availability: "Daily 8AM-10PM",
    verified: true,
  },

  // Hospitals
  {
    id: 16,
    name: "CityCare Hospital",
    category: "Hospitals",
    phone: "+91-9900112233",
    email: "info@citycarehospital.com",
    rating: 4.5,
    reviews: 234,
    description: "Multi-specialty hospital with 24/7 emergency care",
    availability: "24/7 Emergency Care",
    verified: true,
  },
  {
    id: 17,
    name: "Sunrise Multispeciality",
    category: "Hospitals",
    phone: "+91-9911223344",
    email: "contact@sunrisehospital.com",
    rating: 4.7,
    reviews: 189,
    description: "Advanced medical care with experienced specialists",
    availability: "24/7 Emergency Care",
    verified: true,
  },
  {
    id: 18,
    name: "Green Valley Clinic",
    category: "Hospitals",
    phone: "+91-9922334455",
    email: "support@greenvalley.com",
    rating: 4.4,
    reviews: 156,
    description: "Family clinic with general and specialized care",
    availability: "Mon-Sat 8AM-8PM",
    verified: true,
  },
  {
    id: 19,
    name: "Metro General Hospital",
    category: "Hospitals",
    phone: "+91-9933445566",
    email: "metro@hospital.com",
    rating: 4.6,
    reviews: 278,
    description: "Comprehensive healthcare with modern facilities",
    availability: "24/7 Emergency Care",
    verified: true,
  },
  {
    id: 20,
    name: "Heartline Hospital",
    category: "Hospitals",
    phone: "+91-9944556677",
    email: "care@heartline.com",
    rating: 4.8,
    reviews: 167,
    description: "Cardiac care specialists with advanced treatment",
    availability: "24/7 Emergency Care",
    verified: true,
  },

  // Technical Support
  {
    id: 31,
    name: "TechFix IT Solutions",
    category: "Technical Support",
    phone: "+91-9100112233",
    email: "support@techfix.com",
    rating: 4.6,
    reviews: 145,
    description: "Computer repair and IT support services",
    availability: "Mon-Sat 9AM-7PM",
    verified: true,
  },
  {
    id: 32,
    name: "PC Care Hub",
    category: "Technical Support",
    phone: "+91-9111223344",
    email: "help@pccarehub.com",
    rating: 4.5,
    reviews: 98,
    description: "Laptop and desktop repair specialists",
    availability: "Mon-Fri 10AM-6PM",
    verified: true,
  },
  {
    id: 33,
    name: "NetLink Services",
    category: "Technical Support",
    phone: "+91-9122334455",
    email: "netlink@support.com",
    rating: 4.7,
    reviews: 123,
    description: "Network setup and internet connectivity solutions",
    availability: "Mon-Sat 8AM-8PM",
    verified: true,
  },
  {
    id: 34,
    name: "QuickRepair IT",
    category: "Technical Support",
    phone: "+91-9133445566",
    email: "quickrepair@it.com",
    rating: 4.4,
    reviews: 87,
    description: "Fast and reliable IT repair services",
    availability: "Daily 9AM-6PM",
    verified: false,
  },
  {
    id: 35,
    name: "CyberTech Solutions",
    category: "Technical Support",
    phone: "+91-9144556677",
    email: "cybertech@mail.com",
    rating: 4.8,
    reviews: 156,
    description: "Cybersecurity and IT consulting services",
    availability: "Mon-Fri 9AM-5PM",
    verified: true,
  },

  // Tutors & Education
  {
    id: 46,
    name: "BrightFuture Tutors",
    category: "Tutors & Education",
    phone: "+91-9300112233",
    email: "contact@brightfuture.com",
    rating: 4.9,
    reviews: 234,
    description: "Expert tutoring for all subjects and competitive exams",
    availability: "Flexible scheduling",
    verified: true,
  },
  {
    id: 47,
    name: "EduSmart Academy",
    category: "Tutors & Education",
    phone: "+91-9311223344",
    email: "info@edusmart.com",
    rating: 4.7,
    reviews: 189,
    description: "Professional coaching for academic excellence",
    availability: "Mon-Sat 4PM-8PM",
    verified: true,
  },
  {
    id: 48,
    name: "LearnFast Coaching",
    category: "Tutors & Education",
    phone: "+91-9322334455",
    email: "learnfast@edu.com",
    rating: 4.6,
    reviews: 167,
    description: "Fast-track learning programs for students",
    availability: "Daily 3PM-9PM",
    verified: true,
  },
  {
    id: 49,
    name: "SkillUp Tutors",
    category: "Tutors & Education",
    phone: "+91-9333445566",
    email: "skillup@learn.com",
    rating: 4.5,
    reviews: 145,
    description: "Skill development and academic tutoring",
    availability: "Flexible scheduling",
    verified: false,
  },
  {
    id: 50,
    name: "Knowledge Hub",
    category: "Tutors & Education",
    phone: "+91-9344556677",
    email: "hub@knowledge.com",
    rating: 4.8,
    reviews: 198,
    description: "Comprehensive education center for all ages",
    availability: "Mon-Sat 2PM-8PM",
    verified: true,
  },

  // Other Services
  {
    id: 61,
    name: "CleanPro Cleaning Services",
    category: "Other Services",
    phone: "+91-9500112233",
    email: "cleanpro@service.com",
    rating: 4.7,
    reviews: 156,
    description: "Professional residential and commercial cleaning",
    availability: "Mon-Sat 8AM-6PM",
    verified: true,
  },
  {
    id: 62,
    name: "QuickFix Plumbers",
    category: "Other Services",
    phone: "+91-9511223344",
    email: "quickfix@plumbing.com",
    rating: 4.8,
    reviews: 189,
    description: "Emergency plumbing and repair services",
    availability: "24/7 Emergency Service",
    verified: true,
  },
  {
    id: 63,
    name: "Spark Electricians",
    category: "Other Services",
    phone: "+91-9522334455",
    email: "spark@electrician.com",
    rating: 4.6,
    reviews: 134,
    description: "Licensed electrical installation and repair",
    availability: "Mon-Sat 8AM-7PM",
    verified: true,
  },
  {
    id: 64,
    name: "SafeMove Packers",
    category: "Other Services",
    phone: "+91-9533445566",
    email: "safemove@packers.com",
    rating: 4.5,
    reviews: 98,
    description: "Professional packing and moving services",
    availability: "Daily 7AM-7PM",
    verified: true,
  },
  {
    id: 65,
    name: "RideNow Taxi Services",
    category: "Other Services",
    phone: "+91-9544556677",
    email: "ridenow@cab.com",
    rating: 4.4,
    reviews: 267,
    description: "Reliable taxi and cab services",
    availability: "24/7 Service",
    verified: false,
  },
  {
    id: 66,
    name: "Speedy Delivery",
    category: "Other Services",
    phone: "+91-9555667788",
    email: "speedy@delivery.com",
    rating: 4.6,
    reviews: 145,
    description: "Fast courier and delivery services",
    availability: "Mon-Sat 8AM-8PM",
    verified: true,
  },
  {
    id: 67,
    name: "FixIt Home Repairs",
    category: "Other Services",
    phone: "+91-9566778899",
    email: "fixit@home.com",
    rating: 4.7,
    reviews: 123,
    description: "General home maintenance and repair services",
    availability: "Mon-Fri 9AM-6PM",
    verified: true,
  },
  {
    id: 68,
    name: "Shine Laundry",
    category: "Other Services",
    phone: "+91-9577889900",
    email: "shine@laundry.com",
    rating: 4.5,
    reviews: 87,
    description: "Professional laundry and dry cleaning",
    availability: "Mon-Sat 8AM-8PM",
    verified: true,
  },
]

export const categories = [
  { name: "Groceries", count: 15, icon: "🛒", description: "Fresh groceries and daily essentials" },
  { name: "Hospitals", count: 15, icon: "🏥", description: "Medical care and health services" },
  { name: "Technical Support", count: 15, icon: "🔧", description: "IT support and computer repair" },
  { name: "Tutors & Education", count: 15, icon: "📚", description: "Educational services and tutoring" },
  { name: "Other Services", count: 40, icon: "⚡", description: "Home services and utilities" },
]
